import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Settings, LogOut, LockKeyhole } from 'lucide-react';
import { PageHead } from './ui';
type Overview = { user: string; areas: {name:string;modules:number}[]; missions: {title:string;slug:string}[]; resourceCount:number };
export default function Admin() {
  const [overview,setOverview]=useState<Overview|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [username,setUsername]=useState('admin'); const [password,setPassword]=useState('');
  async function load() { const res=await fetch('/api/admin',{credentials:'same-origin'}); const body=await res.json(); if(res.ok) setOverview(body); else if(res.status!==401) setError(body.error||'No pudimos abrir el panel.'); }
  useEffect(()=>{let active=true; fetch('/api/admin',{credentials:'same-origin'}).then(async res=>{const body=await res.json();if(!active)return;if(res.ok)setOverview(body);else if(res.status!==401)setError(body.error||'No pudimos abrir el panel.');}).catch(()=>{if(active)setError('No pudimos conectar con el servidor. Inténtalo nuevamente.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  async function login(e:FormEvent) { e.preventDefault();setBusy(true);setError('');try{const res=await fetch('/api/admin',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',username,password})});const body=await res.json();setPassword('');if(!res.ok)throw new Error(body.error||'No pudimos ingresar.');await load();}catch(e){setError(e instanceof Error?e.message:'No pudimos conectar.');}finally{setBusy(false);} }
  async function logout() { setBusy(true);setError('');try{const res=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});if(!res.ok)throw new Error('No pudimos cerrar la sesión.');setOverview(null);}catch(e){setError(e instanceof Error?e.message:'No pudimos conectar.');}finally{setBusy(false);} }
  if(loading)return <p className="loading" role="status">Comprobando acceso…</p>;
  return <><PageHead eyebrow="ADMINISTRACIÓN · TP PLAY" title={overview?'Panel de administración':'Acceso de administrador'}>{overview?'Consulta el estado actual del sitio y accede a sus contenidos.':'Ingresa con tu usuario y contraseña para abrir el panel.'}</PageHead>{error&&<p className="notice" role="alert">{error}</p>}{overview?<><div className="admin-session"><span><Settings size={20}/> Sesión: <strong>{overview.user}</strong></span><button className="button secondary" disabled={busy} onClick={logout}><LogOut size={17}/>Cerrar sesión</button></div><div className="stats-grid"><div className="stat"><strong>{overview.areas.length}</strong><span>Especialidades</span></div><div className="stat"><strong>{overview.missions.length}</strong><span>Desafíos publicados</span></div><div className="stat"><strong>{overview.resourceCount}</strong><span>Recursos de referencia</span></div></div><section className="panel spaced"><h2>Especialidades</h2>{overview.areas.map(a=><p key={a.name}>{a.name} · {a.modules} módulos</p>)}</section><section className="panel spaced"><h2>Desafíos del sitio</h2><div className="resource-list">{overview.missions.map(m=><Link className="resource-row" key={m.slug} to={`/desafios/${m.slug}`}>{m.title} →</Link>)}</div><p className="muted spaced">Este panel permite consultar los contenidos publicados. La edición de misiones y revisión de evidencias se incorporarán en una siguiente etapa.</p></section></>:<form className="panel admin-login" onSubmit={login}><LockKeyhole size={30}/><h2>Bienvenido, administrador</h2><label className="field">Usuario<input name="username" autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required maxLength={100}/></label><label className="field">Contraseña<input name="password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required maxLength={256}/></label><button className="button" disabled={busy} type="submit">{busy?'Ingresando…':'Ingresar al panel'}</button><p className="muted small">La sesión se cierra después de una hora. Los estudiantes pueden explorar sin registrarse.</p></form>}</>;
}
