export type Area = 'administracion' | 'agropecuaria' | 'parvulos' | 'transversal';
export type Step = { title: string; context: string; prompt: string; kind?: 'number'; options?: string[]; correct: number; feedback: string[]; hint: string; criterion: string };
export type Mission = { slug: string; title: string; subtitle: string; area: Area; module: string; level: '3' | '4'; duration: string; difficulty: string; context: string; goal: string; evidence: string; sourceIds: string[]; steps: Step[]; version: string };
export const areas = [
  { id: 'administracion' as Area, name: 'Administración', fullName: 'Administración mención Recursos Humanos', tag: 'GESTIONA EL FUTURO', description: 'Personas, decisiones y organizaciones que funcionan mejor.', icon: 'briefcase', color: 'violet', modules: ['Gestión Comercial y Tributaria', 'Procesos Administrativos', 'Organización de Oficinas', 'Aplicaciones Informáticas', 'Servicio de Atención de Clientes', 'Utilización de la Información Contable', 'Legislación Laboral', 'Cálculo de Remuneraciones', 'Dotación de Personal', 'Desarrollo y Bienestar Organizacional'] },
  { id: 'agropecuaria' as Area, name: 'Agropecuaria', fullName: 'Agropecuaria', tag: 'CULTIVA SOLUCIONES', description: 'Observa tu entorno. Cuida los recursos. Haz crecer tus ideas.', icon: 'sprout', color: 'green', modules: ['Producción vegetal', 'Producción animal', 'Uso seguro de recursos', 'Sustentabilidad'] },
  { id: 'parvulos' as Area, name: 'Atención de Párvulos', fullName: 'Atención de Párvulos', tag: 'ACOMPAÑA EL APRENDIZAJE', description: 'Imagina experiencias educativas seguras, respetuosas y creativas.', icon: 'heart', color: 'peach', modules: ['Experiencias educativas', 'Bienestar', 'Seguridad', 'Comunicación con familias'] },
];
export const areaName = (id: Area) => areas.find(a => a.id === id)?.name || 'Empleabilidad · Eje transversal';
export const slugify = (value: string) => value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
export const resources = [
  { slug: 'iva-sii', title: 'Comprender el IVA', description: 'Referencia oficial para conocer el impuesto, sus conceptos y su tasa. Complementa el caso simplificado de Misión IVA.', area: 'administracion' as Area, level: '3', format: 'Enlace', author: 'Servicio de Impuestos Internos', url: 'https://www.sii.cl/aprenda_sobre_impuestos/impuestos/impuestos_indirectos.htm', use: 'Consulta en la fuente original; no se redistribuye el documento.' },
  { slug: 'programas-tp', title: 'Explora la formación técnico profesional', description: 'Portal de consulta de bases, especialidades y programas. Las misiones de esta demo aún requieren revisión pedagógica.', area: 'transversal' as Area, level: '3 y 4', format: 'Portal', author: 'Ministerio de Educación de Chile', url: 'https://www.curriculumnacional.cl/curriculum/3o-4o-medio-tecnico-profesional', use: 'Consulta en el sitio original. Revisar la licencia de cada material antes de reutilizarlo.' },
  { slug: 'programa-administracion', title: 'Programa de Administración', description: 'Referencia curricular para la revisión futura de módulos y aprendizajes de Administración.', area: 'administracion' as Area, level: '3 y 4', format: 'Biblioteca', author: 'Ministerio de Educación de Chile', url: 'https://bibliotecadigital.mineduc.cl/handle/20.500.12365/316', use: 'Acceso a la ficha de la biblioteca; condiciones de uso según la fuente.' },
];
export const missions: Mission[] = [
  { slug: 'mision-iva', title: 'Misión IVA', subtitle: 'Los números también cuentan historias.', area: 'administracion', module: 'Gestión Comercial y Tributaria', level: '3', duration: '10–15 min', difficulty: 'Inicial', version: 'demo-1.0', context: 'La cooperativa ficticia Bosque Sur vende cuadernos. Ayuda a organizar sus documentos de un mes. En este caso todas las operaciones están afectas a IVA y las compras cumplen los requisitos del ejercicio para crédito fiscal. No hay exenciones, saldos anteriores ni otras operaciones.', goal: 'Distinguir compras y ventas y calcular un saldo de IVA en un registro simplificado.', evidence: 'Explica por qué el IVA de compras se resta al IVA de ventas en este caso y qué información revisarías antes de usarlo en una empresa real.', sourceIds: ['iva-sii', 'programa-administracion'], steps: [
    { title: 'Ordena los documentos', context: 'Documento A: factura recibida por compra de insumos, neto $100.000, IVA $19.000. Documento B: factura emitida por ventas, neto $200.000, IVA $38.000.', prompt: '¿Cómo registrarías el documento A?', options: ['Como venta de la cooperativa', 'Como compra de la cooperativa', 'Como remuneración del personal'], correct: 1, feedback: ['La cooperativa recibe insumos; no está vendiéndolos en este documento. Revisa quién compra y quién emite.', 'Correcto. La factura recibida corresponde a una compra de insumos. En este caso su IVA es crédito fiscal.', 'Una compra de insumos no es una remuneración. Identifica el bien y el proveedor.'], hint: 'Pregúntate: ¿la cooperativa recibió o entregó los insumos?', criterion: 'Identifica un documento de compra' },
    { title: 'Calcula el IVA de ventas', context: 'Las ventas netas suman $200.000. Para este ejercicio usamos una tasa de IVA de 19%. El valor neto no incluye el impuesto.', prompt: '¿Cuánto es el IVA de las ventas? Ingresa el monto en pesos, sin separadores.', kind: 'number', correct: 38000, feedback: ['Multiplica el neto por 0,19: $200.000 × 0,19 = $38.000. No uses el total con IVA como base.', 'Correcto: $200.000 × 0,19 = $38.000 de IVA de ventas.'], hint: 'Calcula 200000 × 19 ÷ 100.', criterion: 'Calcula el IVA sobre un monto neto' },
    { title: 'Obtén el saldo del caso', context: 'IVA de ventas (débito): $38.000. IVA de compras admitido en este ejercicio (crédito): $19.000. No hay saldos previos ni ajustes.', prompt: '¿Cuál es el saldo de este registro simplificado?', options: ['$57.000, sumando ambos montos', '$19.000, restando crédito al débito', '$38.000, ignorando las compras'], correct: 1, feedback: ['El crédito del ejercicio se descuenta; sumarlo contaría el IVA de compras como una nueva obligación.', 'Correcto: $38.000 − $19.000 = $19.000. Es el saldo del caso ficticio, no una declaración tributaria.', 'El caso sí admite crédito por compras. Ignorarlo omite información necesaria.'], hint: 'Débito menos crédito, usando solo los datos de este caso.', criterion: 'Interpreta débito y crédito del caso' },
  ] },
  { slug: 'rescate-invernadero', title: 'Rescate del invernadero', subtitle: 'Una buena decisión empieza por observar.', area: 'agropecuaria', module: 'Producción vegetal', level: '3', duration: '8–12 min', difficulty: 'Inicial', version: 'demo-1.0', context: 'Son las 11:00 en un invernadero ficticio de lechugas del sur de Chile. El panel muestra 32 °C, suelo húmedo y hojas decaídas. La ventilación está cerrada. Tienes un registro de observación y puedes consultar al encargado.', goal: 'Usar las señales de un caso simulado para elegir acciones y verificar su efecto, sin aplicar tratamientos a ciegas.', evidence: 'Justifica tu secuencia de acciones con dos señales del caso. Describe cómo comprobarías si funcionó.', sourceIds: ['programas-tp'], steps: [
    { title: 'Lee las señales', context: 'Temperatura: 32 °C. Suelo: húmedo. Ventanas: cerradas. Hojas: decaídas. El caso no identifica plagas ni carencias.', prompt: '¿Qué hipótesis conviene revisar primero?', options: ['Falta de agua, sin revisar el suelo', 'Acumulación de calor y ventilación insuficiente', 'Una plaga confirmada'], correct: 1, feedback: ['El suelo ya está húmedo. Agregar agua sin observar puede no resolver la causa.', 'La temperatura alta y la ventilación cerrada justifican revisar primero el calor. Es una hipótesis, no un diagnóstico.', 'No hay evidencia de una plaga. Evita convertir una suposición en un diagnóstico.'], hint: 'Relaciona la temperatura, la humedad y el estado de las ventanas.', criterion: 'Relaciona señales antes de actuar' },
    { title: 'Elige una acción', context: 'El encargado autoriza una medida reversible de ventilación y pide registrar la temperatura. No estás autorizado a aplicar productos.', prompt: '¿Qué haces ahora?', options: ['Aplicas un producto sin identificar el problema', 'Riegas continuamente sin medir', 'Ventilas según la indicación y registras los cambios'], correct: 2, feedback: ['Aplicar productos sin diagnóstico ni autorización no corresponde. En terreno se requiere supervisión.', 'El suelo está húmedo y el caso no indica falta de agua. Mide antes de intervenir.', 'Una acción autorizada y reversible permite observar su efecto. Registra hora, temperatura y estado de las hojas.'], hint: 'Busca una medida autorizada que puedas verificar.', criterion: 'Selecciona una acción prudente y verificable' },
    { title: 'Comprueba el efecto', context: 'Después de ventilar, el registro del caso marca 25 °C y mejoría parcial de las hojas. Algunas plantas aún están decaídas.', prompt: '¿Cómo continúas?', options: ['Das por resuelto todo y dejas de observar', 'Registras la mejoría y consultas por las plantas que siguen decaídas', 'Duplicas el riego automáticamente'], correct: 1, feedback: ['Una mejoría parcial no confirma que todo esté resuelto. Continúa observando.', 'Correcto. Documentar y consultar evita ignorar señales que podrían requerir otra revisión.', 'El caso no aporta evidencia de falta de agua. No intensifiques una acción sin evaluar.'], hint: 'Distingue una mejoría parcial de una solución comprobada.', criterion: 'Verifica y comunica el resultado' },
  ] },
  { slug: 'primera-entrevista', title: 'Tu primera entrevista', subtitle: 'Tu experiencia empieza antes del primer trabajo.', area: 'transversal', module: 'Emprendimiento y empleabilidad', level: '4', duration: '8–12 min', difficulty: 'Inicial', version: 'demo-1.0', context: 'Te preparas para una entrevista ficticia de práctica. No necesitas experiencia laboral previa: puedes usar ejemplos de clases, proyectos y trabajo en equipo. La empresa te pregunta cómo aprendes y colaboras.', goal: 'Elegir respuestas claras y respetuosas y construir una presentación con un ejemplo concreto.', evidence: 'Escribe una presentación de 3 a 5 frases: qué estudias, una habilidad, un ejemplo de un proyecto y qué te gustaría aprender. Evita datos personales sensibles.', sourceIds: ['programas-tp'], steps: [
    { title: 'Presenta una habilidad', context: 'La entrevistadora pregunta: «¿Qué puedes aportar al equipo?» Puedes recordar un proyecto escolar en el que organizaste las tareas.', prompt: '¿Qué respuesta aporta mejor evidencia?', options: ['«Soy el mejor en todo, aunque no tengo ejemplos»', '«En un proyecto organicé las tareas y revisamos juntos las entregas»', '«No tengo experiencia, así que no puedo aportar»'], correct: 1, feedback: ['Una afirmación muy amplia sin ejemplos es difícil de comprender. Describe una situación real.', 'Un ejemplo escolar muestra acciones concretas. Cuenta qué hiciste y qué aprendiste.', 'Tus proyectos y experiencias de aprendizaje también permiten mostrar habilidades.'], hint: 'Una habilidad se entiende mejor con una situación y una acción.', criterion: 'Comunica una habilidad con evidencia' },
    { title: 'Responde a lo desconocido', context: 'Te preguntan por una herramienta que aún no has utilizado. Es una oportunidad para mostrar cómo aprendes.', prompt: '¿Qué respuesta elegirías?', options: ['«La domino», aunque no sea cierto', '«No la conozco; revisaría la guía y pediría acompañamiento para practicar»', 'Cambias de tema sin responder'], correct: 1, feedback: ['Afirmar experiencia inexistente genera expectativas que no podrás sostener. Sé claro sobre lo que sabes.', 'Reconocer lo que falta y proponer cómo aprenderlo muestra honestidad e iniciativa.', 'Responder directamente ayuda a mantener una comunicación clara.'], hint: 'Puedes ser honesto y proponer un plan de aprendizaje al mismo tiempo.', criterion: 'Expresa una estrategia para aprender' },
    { title: 'Cierra la conversación', context: 'Al finalizar te dicen: «¿Tienes alguna pregunta?» Quieres comprender el acompañamiento de la práctica.', prompt: '¿Qué pregunta te ayuda a conocer la experiencia?', options: ['«¿Qué tareas realizaría y cómo recibiría orientación al comienzo?»', '«¿Puedo no cumplir ninguna de las tareas?»', 'No preguntas porque te parece obligatorio saber todo'], correct: 0, feedback: ['Preguntar por tareas y acompañamiento aclara expectativas y facilita una práctica responsable.', 'Es válido consultar condiciones, pero esta formulación no ayuda a entender responsabilidades.', 'No necesitas saberlo todo. Preguntar con respeto es parte de una buena comunicación.'], hint: 'Pregunta por tareas, expectativas y apoyo para aprender.', criterion: 'Formula una pregunta pertinente' },
  ] },
];
export const learningRoutes = [
  { id: 'primer-emprendimiento', title: 'Organiza tu primer emprendimiento', description: 'De los documentos de una pequeña empresa a comunicar tus habilidades.', missions: ['mision-iva', 'primera-entrevista'], icon: 'rocket' },
  { id: 'practica', title: 'Prepárate para tu práctica', description: 'Construye una presentación y explica cómo aportarías a un equipo.', missions: ['primera-entrevista'], icon: 'briefcase' },
];
