import { Component, useEffect, useRef, useState, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link, NavLink, useLocation, useNavigate } from 'react-router-dom';
import { Menu, X, Search, ArrowUpRight, WifiOff, AlertCircle, Compass, Settings } from 'lucide-react';
import { DemoProvider, useDemo } from './store';
import { Logo } from './ui';
import { Player, Results, Missing } from './Player';
import { Home, Catalog, MissionDetail, Specialties, Specialty, Library, ResourceDetail, Dashboard, LearningRoute, HowItWorks, Teacher, Access, Profile, Info } from './pages';
import Admin from './Admin';
import './styles.css';

class ErrorBoundary extends Component<{children:ReactNode},{failed:boolean}> {
  state={failed:false}; static getDerivedStateFromError(){return {failed:true};}
  render(){return this.state.failed?<main className="fatal"><h1>La página necesita un nuevo intento.</h1><p>No pudimos completar la acción. Recarga para recuperar el avance guardado en este navegador.</p><button className="button" onClick={()=>window.location.reload()}>Recargar</button></main>:this.props.children;}
}
function Header() {
  const [open,setOpen]=useState(false); const [searchOpen,setSearchOpen]=useState(false); const [query,setQuery]=useState(''); const toggle=useRef<HTMLButtonElement>(null);const location=useLocation();const navigate=useNavigate();
  useEffect(()=>{setOpen(false);setSearchOpen(false);},[location.pathname,location.search]);
  useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);setSearchOpen(false);toggle.current?.focus();}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[]);
  const nav=[['Inicio','/'],['Especialidades','/especialidades'],['Desafíos','/desafios'],['Recursos','/recursos'],['Cómo funciona','/como-funciona']];
  return <header className="site-header"><div className="header-inner"><Logo/><nav aria-label="Navegación principal" className={`main-nav ${open?'open':''}`} id="main-nav">{nav.map(([label,to])=><NavLink key={to} to={to} end={to==='/'}>{label}</NavLink>)}<Link className="mobile-learning" to="/mi-aprendizaje">Mi aprendizaje demo</Link></nav><div className="header-actions"><Link className="icon-button admin-gear" to="/admin" aria-label="Acceso de administrador" title="Administración"><Settings size={23}/></Link><Link className="learning-icon" aria-label="Mi aprendizaje de demostración" to="/mi-aprendizaje"><Compass size={21}/></Link><button className="icon-button" aria-label={searchOpen?'Cerrar búsqueda':'Buscar desafíos'} aria-expanded={searchOpen} onClick={()=>setSearchOpen(!searchOpen)}><Search size={21}/></button><Link className="login-link" to="/ingresar">Ingresar <ArrowUpRight size={16}/></Link><button ref={toggle} className="icon-button menu-toggle" aria-label={open?'Cerrar menú':'Abrir menú'} aria-expanded={open} aria-controls="main-nav" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{searchOpen&&<form className="header-search" onSubmit={e=>{e.preventDefault();navigate(`/desafios?q=${encodeURIComponent(query)}`);}}><label className="search-field"><Search size={20}/><span className="sr-only">Buscar una misión</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="¿Qué quieres aprender hoy?"/></label><button className="button" type="submit">Buscar</button></form>}</header>;
}
function Layout() {
  const location=useLocation();const main=useRef<HTMLElement>(null);const {state,saveError,retry}=useDemo();const [online,setOnline]=useState(navigator.onLine);
  useEffect(()=>{window.scrollTo(0,0);main.current?.focus({preventScroll:true});document.title=`TP PLAY — ${location.pathname==='/'?'Aprende jugando. Construye tu futuro.':location.pathname.startsWith('/desafios')?'Desafíos':location.pathname.startsWith('/mi-aprendizaje')?'Mi aprendizaje':'Explora el campus'}`;},[location.pathname]);
  useEffect(()=>{const update=()=>setOnline(navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
  return <div className={state.reducedMotion?'reduced-motion':''}><a className="skip-link" href="#contenido">Saltar al contenido</a><Header/>{!online&&<div className="status-banner" role="status"><WifiOff size={18}/><span>Estás sin conexión. Las misiones ya cargadas pueden continuar; los enlaces externos necesitan internet.</span><button className="text-button" onClick={()=>setOnline(navigator.onLine)}>Comprobar conexión</button></div>}{saveError&&<div className="status-banner" role="alert"><AlertCircle size={18}/><span>{saveError}</span><button className="button secondary" onClick={retry}>Reintentar guardado</button></div>}
    <main id="contenido" ref={main} tabIndex={-1} className="container"><Routes>
      <Route path="/" element={<Home/>}/><Route path="/especialidades" element={<Specialties/>}/><Route path="/especialidades/:slug" element={<Specialty/>}/><Route path="/especialidades/:slug/modulos/:modulo" element={<Specialty/>}/>
      <Route path="/desafios" element={<Catalog/>}/><Route path="/desafios/:slug" element={<MissionDetail/>}/><Route path="/desafios/:slug/jugar" element={<Player/>}/><Route path="/intentos/:id/resultados" element={<Results/>}/>
      <Route path="/recursos" element={<Library/>}/><Route path="/recursos/:slug" element={<ResourceDetail/>}/><Route path="/como-funciona" element={<HowItWorks/>}/><Route path="/mi-aprendizaje" element={<Dashboard/>}/><Route path="/mi-aprendizaje/rutas/:id" element={<LearningRoute/>}/>
      <Route path="/docente" element={<Teacher/>}/><Route path="/docente/*" element={<Info kind="denegado"/>}/><Route path="/admin" element={<Admin/>}/><Route path="/ingresar" element={<Access/>}/><Route path="/recuperar-acceso" element={<Info kind="recuperar"/>}/><Route path="/perfil" element={<Profile/>}/><Route path="/ayuda" element={<Info kind="ayuda"/>}/><Route path="/privacidad" element={<Info kind="privacidad"/>}/><Route path="/condiciones" element={<Info kind="condiciones"/>}/><Route path="*" element={<Missing/>}/>
    </Routes></main><footer className="site-footer"><div className="container footer-top"><div><Logo/><p>Aprende jugando.<br/>Construye tu futuro.</p><span className="pill">Prototipo de demostración</span></div><div><h3>Explora</h3><Link to="/especialidades">Especialidades</Link><Link to="/desafios">Desafíos</Link><Link to="/recursos">Fuentes educativas</Link><Link to="/como-funciona">Cómo funciona</Link></div><div><h3>Tu recorrido</h3><Link to="/mi-aprendizaje">Mi aprendizaje demo</Link><Link to="/perfil">Preferencias</Link><Link to="/docente">Espacio docente</Link></div><div><h3>Conversemos</h3><Link to="/ayuda">Ayuda y contacto</Link><Link to="/privacidad">Privacidad</Link><Link to="/condiciones">Condiciones</Link><a href="https://github.com/marcelobarriaar-sketch/tpplay" target="_blank" rel="noreferrer">Proyecto en GitHub ↗</a></div></div><div className="container creator-signature"><p>Sitio creado por el docente TP <strong>Marcelo Barría Arismendi</strong></p><div><a href="tel:+56930357842">Contacto: +56 9 3035 7842</a><a href="mailto:marcelo.barriaar@gmail.com">marcelo.barriaar@gmail.com</a></div></div><div className="container footer-bottom"><span>© 2026 TP PLAY</span><span>Hecho para aprender. Diseñado para volver a intentar.</span><span>Etapa 1 · Estudiantes invitados</span></div></footer></div>;
}
createRoot(document.getElementById('root')!).render(<ErrorBoundary><BrowserRouter><DemoProvider><Layout/></DemoProvider></BrowserRouter></ErrorBoundary>);
